SELECT E.CODE, N.BLACK_LISTED
FROM ENROLLMENT_REF E, NODE N
WHERE E.ID = N.ENROLLMENT_REF
AND E.CODE IN (
);

UPDATE NODE SET BLACK_LISTED = FALSE
WHERE ENROLLMENT_REF IN 
(SELECT ID FROM ENROLLMENT_REF 
WHERE CODE IN (
);