select * from USER_ID                                   order by 1 desc ;
select * from BASIC_DATA                                order by 1 desc ;
select * from DYNAMIC_DATA                              order by 1 desc ;
select * from ENROLLMENT_LOG                            order by 1 desc ;
select * from MSISDN_DETAIL                             order by 1 desc ;
select * from META_DATA                                 order by 1 desc ;
select * from PHONE_NUMBER_STATUS                       order by 1 desc ;
select * from SMS_ACTIVATION_REQUEST                    order by 1 desc ;
select * from BFP_SYNC_LOG                              order by 1 desc ;
select * from BFP_FAILURE_LOG                           order by 1 desc ;
select * from MSISDN_PROVISION_STATUS                   order by 1 desc ;
select * from MSISDN_PROVISION_STATUS_LOG               order by 1 desc ;
select * from AGILITY_PUSH_STATUS                       order by 1 desc ;
select * from SIGNATURE                                 order by 1 desc ;
select * from PASSPORT_DETAIL                           order by 1 desc ;
select * from PASSPORT                                  order by 1 desc ;
select * from WSQ_IMAGE                                 order by 1 desc ;
select * from SPECIAL_DATA                              order by 1 desc ;
select * from INFRACTION                                order by 1 desc ;
select * from EYEBALLING                                order by 1 desc ;
select * from EYEBALLING_LOG                            order by 1 desc ;
select * from KYC_AGILITY_MAPPER                        order by 1 desc ;
select * from ACTIVATION_SYNC_LOG                       order by 1 desc ;
select * from ACTIVATION_RETRY_LOG                      order by 1 desc ;
select * from SIM_SWAP_DEMOGRAPHIC                      order by 1 desc ;
select * from SIM_SWAP_DEMOGRAPHIC_LOG 					order by 1 desc ;


SELECT * FROM SETTING                           order by 1 desc ;
SELECT * FROM COMMUNITY_                        order by 1 desc ;
SELECT * FROM PAGE_                             order by 1 desc ;
SELECT * FROM KM_ROLE_COMMUNITY_MAPPER          order by 1 desc ;
SELECT * FROM SIMROP_AGENT_TREND                order by 1 desc ;
SELECT * FROM SIMROP_REGISTRATION_TREND         order by 1 desc ;
SELECT * FROM PASSwORD_POLICY                   order by 1 desc ;
SELECT * FROM UNTAGGING_HISTORY                 order by 1 desc ;
SELECT * FROM BIB_BSL                           order by 1 desc ;
SELECT * FROM AUTHENTICATION_MODE				order by 1 desc ;


select * from DEALER TYPE               order by 1 desc ;
select * from DEALER DIVISION           order by 1 desc ;
select * from KYC DEALER                order by 1 desc ;
select * from KM USER                   order by 1 desc ;
select * from OUTLET TYPE               order by 1 desc ;
select * from OUTLET                    order by 1 desc ;
select * from KM_ROLE                   order by 1 desc ;
select * from USER_ROLE                 order by 1 desc ;
select * from KM_PRIVILEGE              order by 1 desc ;
select * from KM_ROLE_PRIVILEGE         order by 1 desc ;
select * from LEVEL_GROUP               order by 1 desc ;
select * from USER_LEVEL 				order by 1 desc ;